####################################################
#
# Welcome to Tokyo Jekyll Theme
# Author Link : https://themeix.com/
# Version : v1.0.2
#
####################################################

# Site settings
title: "Nader Lobandi"
email: "Lobandi.n@northeastern.edu"
baseurl: "" # the subpath of your site, e.g. /blog
url: "www.linkedin.com/in/naderlobandi" # the base hostname & protocol for your site, e.g. http://example.com
logo: /assets/images/header-brand.png
description: "Personal Website"
keywords: "Nader, Lobandi, NADER1196, Northeastern, Data science, Boston, Massachusetts"
# mailchimp: "https://themeix.us16.list-manage.com/subscribe/post?u=307862c135e4548eecf86f389&amp;id=4784863884"
facebook: https://m.facebook.com/nader.lobandi.1
instagram: https://instagram.com/nader.lobandi?utm_medium=copy_link
# twitter: https://twitter.com/themeix_com

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag

collections:
  authors:
    output: true
    permalink: /author/:path/

feed:
  collections:
    posts:
      path: "/index.xml"
